image: node:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - sed -i '11s/\//\.\//' docusaurus.config.js
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - mv ./build ../public
  artifacts:
    paths:
      - public
  dependencies:
    - test

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH