image: node:15.12-alpine3.13

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apk update
    - apk install git
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  script:
    - mv ./build ../public
  artifacts:
    paths:
      - public
  dependencies:
    - test

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH